flags: {}

resolver: lts-3.16

# compiler: ghcjs-0.2.0.20151029_ghc-7.10.2
compiler:  ghcjs-0.2.0.20151209_ghc-7.10.2

compiler-check: match-exact

setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.20151209_ghc-7.10.2:
        url: "https://agithub.com/nrolland/ghcjs/releases/download/v0.2.0.20151029/ghcjs-0.2.0.20151029.tar.gz"

packages:
- location: '.'
#- location:
#    git: https://github.com/ryantrinkle/reflex-dom.git
#    commit: f4dbdd799260bc203f7f5cdce18362cb896f6d57 # ghcjs-improved-base-2 branch
- location:
    git: https://github.com/ocharles/Francium.git
#    commit: 82584a12ff184ad63bd2311f3672967709e57ab2 # ghcjs-improved-base-2 branch
    commit: a5f2be9e0c4e5c193400783132825f387592378e
- location:
     git: https://github.com/ocharles/virtual-dom.git
     commit: 82c3fc6e3eac9623f0d27f4cf7bb8cd4ecdf4e71
  extra-dep: true

extra-deps:
  - reflex-0.3.2
  - ref-tf-0.4
  - these-0.6.1.0
  - ghcjs-dom-0.2.3.0
  - reactive-banana-0.9.0.0
