flags: {}

resolver: lts-3.17
compiler:  ghcjs-0.2.0.20151209_ghc-7.10.2
compiler-check: match-exact

setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.20151209_ghc-7.10.2:
        url: "https://raw.githubusercontent.com/tolysz/video/ghcjs/ghcjs-0.2.0.20151209_ghc-7.10.2.tar.gz"

packages:
- location: '.'
#- location:
#      git: git@github.com:tolysz/aeson
#      commit: de2736778ff880d739d24f3c78dd028b94cc5cd0
#  extra-dep: true
- location:
    git: https://github.com/ryantrinkle/reflex.git
    commit: 784f9f79396ae713a03fc4d81f8a67b75d6ade1c # need a few package bumps not present in hackage release yet
  extra-dep: true
- location:
    git: https://github.com/ryantrinkle/reflex-dom.git
    commit: a60ae687cdc284a8eb3776fc95aa2adefc51e7ec # hamishmack-master (improved-base compatible)
  extra-dep: true

extra-deps:
  - reflex-0.3.2
  - ref-tf-0.4
  - these-0.6.1.0
  - ghcjs-dom-0.2.3.0
