language: haskell

before_install:
env:
 - GHCVER=7.8.4 CABALVER=1.22
# - GHCVER=7.10.1 CABALVER=1.22
# - GHCVER=head  CABALVER=head

matrix:
  allow_failures:
   - env: GHCVER=7.10.1 CABALVER=1.22
   - env: GHCVER=head  CABALVER=head

before_install:
 - npm -g install coffee-script
 - coffee --version
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$HOME/.cabal/bin:$PATH
 - gcc --version
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt-get -qq update
 - sudo apt-get -qq install gcc-4.8
 - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 90
 - gcc --version
 - cabal --version
 - echo $GHCVER $CABALVER
 - travis_retry cabal update
 - cabal install alex happy

install:
 - cabal sandbox init
 - cabal install aeson-0.8.0.2.tar.gz haxl-0.1.0.0.tar.gz
 - cabal install --only-dependencies --enable-tests

script:
 - cabal configure --enable-tests --disable-shared
 #--enable-library-coverage || cabal configure --disable-executable-dynamic --disable-shared  --enable-tests --enable-coverage
 - cabal build
# - cabal test

#after_script:
# - cabal install hpc-coveralls
# - hpc-coveralls --exclude-dir=test test
