language: haskell

before_install:
env:
 - GHCVER=7.8.4 CABALVER=1.22
 - GHCVER=7.10.1 CABALVER=1.22
# - GHCVER=head  CABALVER=head

matrix:
  allow_failures:
   - env: GHCVER=7.10.1 CABALVER=1.22
   - env: GHCVER=head  CABALVER=head

before_install:
 - npm -g install coffee-script
 - coffee --version
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$HOME/.cabal/bin:$PATH
 - gcc --version
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt-get -qq update
 - sudo apt-get -qq install gcc-4.8
 - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 90
 - gcc --version
 - cabal --version
 - echo $GHCVER $CABALVER
 - travis_retry cabal update
 - cabal install alex happy

install:
 - cd /home/travis
 - git clone --depth=50 --branch=MissingDefault2 https://github.com/tolysz/aeson tolysz/aeson
 - git clone --depth=50 --branch=master https://github.com/tolysz/google-api tolysz/google-api
 - git clone --depth=50 --branch=master https://github.com/tolysz/http-client-extra tolysz/http-client-extra
 - git clone --depth=50 --branch=master https://github.com/tolysz/http-client-extra-oauth2 tolysz/http-client-extra-oauth2
 - git clone --depth=50 --branch=master https://github.com/tolysz/yesod-websockets-extra tolysz/yesod-websockets-extra
 - git clone --depth=50 --branch=master https://github.com/tolysz/yesod-angular-ui tolysz/yesod-angular-ui

 - cd $TRAVIS_BUILD_DIR
 - cabal sandbox init
 - cabal sandbox add-source /home/travis/tolysz/aeson
 - cabal sandbox add-source /home/travis/tolysz/google-api
 - cabal sandbox add-source /home/travis/tolysz/http-client-extra
 - cabal sandbox add-source /home/travis/tolysz/http-client-extra-oauth2
 - cabal sandbox add-source /home/travis/tolysz/yesod-websockets-extra
 - cabal sandbox add-source /home/travis/tolysz/yesod-angular-ui
 - cabal install --only-dependencies --enable-tests 

script:
 - cabal configure --enable-tests --disable-shared
 #--enable-library-coverage || cabal configure --disable-executable-dynamic --disable-shared  --enable-tests --enable-coverage
 - cabal build
# - cabal test

#after_script:
# - cabal install hpc-coveralls
# - hpc-coveralls --exclude-dir=test test
