language: sh # Halcyon will handle all Haskell dependencies

env:
  global:
     - HALCYON_GHC_VERSION=7.10.2-rc1 HALCYON_CABAL_VERSION=1.22.6.0
#     - HALCYON_GHC_VERSION=7.8.4 HALCYON_CABAL_VERSION=1.20.6.0
    # http://docs.travis-ci.com/user/environment-variables/#Secure-Variables
#    - secure: ... # HALCYON_AWS_ACCESS_KEY_ID
#    - secure: ... # HALCYON_AWS_SECRET_ACCESS_KEY
#    - secure: ... # HALCYON_S3_BUCKET

before_install:
  - sudo mkdir -p /app
  - sudo chown $USER /app
  - git clone https://github.com/mietek/halcyon.git /app/halcyon

install:
  - travis_wait /app/halcyon/halcyon build
  - /app/halcyon/halcyon paths > halcyon-env
  - ln -sf /app/sandbox/cabal.sandbox.config cabal.sandbox.config

script:
  - source halcyon-env && cabal configure --enable-tests && cabal test
