# Values formatted like "_env:ENV_VAR_NAME:default_value" can be overridden by the specified environment variable.
# See https://github.com/yesodweb/yesod/wiki/Configuration#overriding-configuration-values-with-environment-variables

static-dir:     "_env:STATIC_DIR:static"
host:           "_env:HOST:*4" # any IPv4 host
port:           "_env:PORT:3000"
approot:        "_env:APPROOT:http://localhost:3000"
app-static-root: "_env:APPSTATICROOT"
ip-from-header: "_env:IP_FROM_HEADER:false"

# Optional values with the following production defaults.
# In development, they default to the inverse.
#
development: false
detailed-logging: false
should-log-all: false
reload-templates: false
mutable-static: false
skip-combining: false

database:
  user:     "_env:PGUSER:video"
  password: "_env:PGPASS:video"
  host:     "_env:PGHOST:localhost"
  port:     "_env:PGPORT:5432"
  database: "_env:PGDATABASE:video"
  poolsize: "_env:PGPOOLSIZE:10"

neo4j:
  host: "_env:NEO_DB"
  auth: "_env:NEO_AUTH"

analytics: "_env:GOOGLE_ANALYTICS"

copyright: "2015© Marcin Tolysz website, content various copyrights"


google-api-server: "_env:GOOGLE_API_SERVER"
google-api-browser: "_env:GOOGLE_API_BROWSER"
google-site-verification: "_env:GOOGLE_SITE_VERIFICATION"

google-oauth:
#  auth_uri: "https://accounts.google.com/o/oauth2/auth"
# token_uri: "https://accounts.google.com/o/oauth2/token"
#  revoke_uri: "https://accounts.google.com/o/oauth2/revoke"
   client_id:             "_env:CLIENT_ID:"
   client_secret:         "_env:CLIENT_SECRET:"
   client_email:          "_env:CLIENT_EMAIL:"
   client_x509_cert_url:  "_env:CLIENT_X509_CERT_URL:"
#  auth_provider_x509_cert_url: "https://www.googleapis.com/oauth2/v1/certs"
#  javascript_origins: ["https://video.kio.sx"]

# Facebook login button/ register with https://developers.facebook.com/apps/
facebook-app-name:   "_env:FACEBOOK_APP_NAME"
facebook-app-id:     "_env:FACEBOOK_APP_ID"
facebook-app-secret: "_env:FACEBOOK_APP_SECRET"
