LangId: en-GB
Demos: Demos
Hello: Hello
FullName: Full name
ShortName: Short name
Notes: Notes
GroupIsPublic: group is public
Group: Group
Url: Url
Create: Create
Add: Add
Save: Save
XDelete: Delete
Edit: Edit

UserEmail: Email
UserName: Full name
UserFriendly: Friendly
UserSiteAdmin: site admin
UserAvatar: Avatar

ClosePanel: Close Panel
Logout: Logout
Login: Login

SwitchLanguage: Change Language to:
Switch: Change

MenuAdmin: Admin
AllUsers: All Users
AddNewUser: Add New User
AddNewGroup: Add new group
EditUser: Edit user
EditGroup: Edit
AddUserToGroup: Add user to this group

MenuSite:  Site
MenuChat:  Chat

ChatShout: Shout
ChatSend: Send

MenuAdminVideo: Video
MenuAdminGroup: Group
MenuAdminUsers: Users

LoginOr: OR
LoginUsing: Login Using:

ShareWith: Share with:

S1Short: me
S1Long: only you

S2Short: people from meeting
S2Long: all people who seen it anyway

S3Short: only members
S3Long: people who are members of your Toastmaster

S4Short: channel members
S4Long: all members and friends (i.e. guests)

S5Short: site members
S5Long: all other Toastmaster groups

S6Short: the youtube
S6Long: Everyone! this is going into the public playlist viewable by everyone

NewMember: New group member
EmailLong: Email address
FullMember: full group member
UserAdmin: member is user admin
VideoAdmin: member ia video admin