LangId: pl
Demos: Dema
Hello: Hejka
FullName: Pełna nazwa
ShortName: Skrócona nazwa
Notes: Opis
GroupIsPublic: grupa jest publiczna
Group: Grupa
Url: link do strony
Create: utwóż
Add: Dodaj
Save: zapisz
XDelete: Usuń
Edit: edytuj

UserEmail: email
UserName: Pełne Imię i Nazwisko
UserFriendly: ksywka
UserSiteAdmin: adminitrator kanału
UserAvatar: Obrazek

ClosePanel: Zamknij panel
Logout: Wyloguj

SwitchLanguage: Zmień język na:
Switch: Zmień

MenuAdmin: Administracja
AllUsers: Wszyscy użytkownicy
AddNewUser: Nowy użytkownik
AddNewGroup: Nowa grupa
EditUser: Edytuj użytkownika
EditGroup: Edytuj grupę
AddUserToGroup: Dodaj użytkownika do tej grupy

MenuSite:  Site
MenuChat:  Czat

ChatShout: Krzycz
ChatSend: wyślij

MenuAdminVideo: Klipy wideo
MenuAdminGroup: Grupy
MenuAdminUsers: Użytkownicy

LoginOr: lub
LoginUsing: Zaloguj się przez:

ShareWith: Udostępnij:

S1Short: Sobie
S1Long: Tylko Ja

S2Short: ludzie ze spotkania
S2Long: ludzie którzy już i tak to widzieli

S3Short: Tylko członkowie klubu
S3Long: Osoby które są członkami twojego klubu Toastmaster

S4Short: Użytkownicy tego kanału
S4Long: Członkowie oraz osoby zaakceptowane do kanału (tzn. goście czy byli członkowie)

S5Short: Członkowie dowolnego klubu
S5Long: Członkowie innych kanałów na stronie.

S6Short: Youtube
S6Long: Każdy! To będzie publiczne wideo który każdy będzie mógł obejżeć

NewMember: Dodawanie członków kanału
EmailLong: Adres poczty elektronicznej
FullMember: Pełnoprawny członek klubu
UserAdmin: Uprawnienia do zarządzania użytkownikami
VideoAdmin: Uprawnienia do zarządzania klipami wideo